---
engines:
  coverage:
    enabled: true
  duplication:
    enabled: true
  eslint:
    enabled: true
  markdownlint:
    enabled: true
  metric:
    enabled: true
  remark-lint:
    enabled: true
  stylelint:
    enables: true
  tslint:
    enabled: false
languages:
  css:
    extensions:
      - '-css.resource'
exclude_paths:
  - '.github/**'
  - '.vscode/**'
  - 'docs/**'
  - 'docs-tmp/**'
  - 'commitlint.config.js'
