---
engines:
  duplication:
    enabled: true
  metric:
    enabled: true
  remark-int:
    enabled: true
  coverage:
    enabled: true
  eslint:
    enabled: true
  tslint:
    enabled: false
languages:
  css:
    extensions:
      - '-css.resource'
exclude_paths:
  - '.github/**'
  - '.vscode/**'
  - 'docs/**'
  - 'docs-tmp/**'
  - '**.md'
  - 'commitlint.config.js'
